name: Docker Publish Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - name: Checkout Repository  
      uses: actions/checkout@v4

    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: neyo386/workflows
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
